var winners = [{"name":"Janet Gaynor","film":"3 roles; see note[1]","date":"May 16, 1929","age":22 ,"gender":"female","role":"Best Actress"},
{"name":"Mary Pickford","film":"Coquette","date":"April 3, 1930","age":37 ,"gender":"female","role":"Best Actress"},
{"name":"Norma Shearer","film":"The Divorcee","date":"November 5, 1930","age":28 ,"gender":"female","role":"Best Actress"},
{"name":"Marie Dressler","film":"Min and Bill","date":"November 10, 1931","age":63 ,"gender":"female","role":"Best Actress"},
{"name":"Helen Hayes","film":"The Sin of Madelon Claudet","date":"November 18, 1932","age":32 ,"gender":"female","role":"Best Actress"},
{"name":"Katharine Hepburn","film":"Morning Glory","date":"March 16, 1934","age":26 ,"gender":"female","role":"Best Actress"},
{"name":"Claudette Colbert","film":"It Happened One Night","date":"February 27, 1935","age":31 ,"gender":"female","role":"Best Actress"},
{"name":"Bette Davis","film":"Dangerous","date":"March 5, 1936","age":27 ,"gender":"female","role":"Best Actress"},
{"name":"Luise Rainer","film":"The Great Ziegfeld","date":"March 4, 1937","age":27 ,"gender":"female","role":"Best Actress"},
{"name":"Luise Rainer","film":"The Good Earth","date":"March 10, 1938","age":28 ,"gender":"female","role":"Best Actress"},
{"name":"Bette Davis","film":"Jezebel","date":"February 23, 1939","age":30 ,"gender":"female","role":"Best Actress"},
{"name":"Vivien Leigh","film":"Gone with the Wind","date":"February 29, 1940","age":26 ,"gender":"female","role":"Best Actress"},
{"name":"Ginger Rogers","film":"Kitty Foyle","date":"February 27, 1941","age":29 ,"gender":"female","role":"Best Actress"},
{"name":"Joan Fontaine","film":"Suspicion","date":"February 26, 1942","age":24 ,"gender":"female","role":"Best Actress"},
{"name":"Greer Garson","film":"Mrs. Miniver","date":"March 4, 1943","age":38 ,"gender":"female","role":"Best Actress"},
{"name":"Jennifer Jones","film":"The Song of Bernadette","date":"March 2, 1944","age":25 ,"gender":"female","role":"Best Actress"},
{"name":"Ingrid Bergman","film":"Gaslight","date":"March 15, 1945","age":29 ,"gender":"female","role":"Best Actress"},
{"name":"Joan Crawford","film":"Mildred Pierce","date":"March 7, 1946","age":41 ,"gender":"female","role":"Best Actress"},
{"name":"Olivia de Havilland","film":"To Each His Own","date":"March 13, 1947","age":30 ,"gender":"female","role":"Best Actress"},
{"name":"Loretta Young","film":"The Farmer's Daughter","date":"March 20, 1948","age":35 ,"gender":"female","role":"Best Actress"},
{"name":"Jane Wyman","film":"Johnny Belinda","date":"March 24, 1949","age":32 ,"gender":"female","role":"Best Actress"},
{"name":"Olivia de Havilland","film":"The Heiress","date":"March 23, 1950","age":33 ,"gender":"female","role":"Best Actress"},
{"name":"Judy Holliday","film":"Born Yesterday","date":"March 29, 1951","age":29 ,"gender":"female","role":"Best Actress"},
{"name":"Vivien Leigh","film":"A Streetcar Named Desire","date":"March 20, 1952","age":38 ,"gender":"female","role":"Best Actress"},
{"name":"Shirley Booth","film":"Come Back, Little Sheba","date":"March 19, 1953","age":54 ,"gender":"female","role":"Best Actress"},
{"name":"Audrey Hepburn","film":"Roman Holiday","date":"March 25, 1954","age":24 ,"gender":"female","role":"Best Actress"},
{"name":"Grace Kelly","film":"The Country Girl","date":"March 30, 1955","age":25 ,"gender":"female","role":"Best Actress"},
{"name":"Anna Magnani","film":"The Rose Tattoo","date":"March 21, 1956","age":48 ,"gender":"female","role":"Best Actress"},
{"name":"Ingrid Bergman","film":"Anastasia","date":"March 27, 1957","age":41 ,"gender":"female","role":"Best Actress"},
{"name":"Joanne Woodward","film":"The Three Faces of Eve","date":"March 26, 1958","age":28 ,"gender":"female","role":"Best Actress"},
{"name":"Susan Hayward","film":"I Want to Live!","date":"April 6, 1959","age":41 ,"gender":"female","role":"Best Actress"},
{"name":"Simone Signoret","film":"Room at the Top","date":"April 4, 1960","age":39 ,"gender":"female","role":"Best Actress"},
{"name":"Elizabeth Taylor","film":"BUtterfield 8","date":"April 17, 1961","age":29 ,"gender":"female","role":"Best Actress"},
{"name":"Sophia Loren","film":"Two Women","date":"April 9, 1962","age":27 ,"gender":"female","role":"Best Actress"},
{"name":"Anne Bancroft","film":"The Miracle Worker","date":"April 8, 1963","age":31 ,"gender":"female","role":"Best Actress"},
{"name":"Patricia Neal","film":"Hud","date":"April 13, 1964","age":38 ,"gender":"female","role":"Best Actress"},
{"name":"Julie Andrews","film":"Mary Poppins","date":"April 5, 1965","age":29 ,"gender":"female","role":"Best Actress"},
{"name":"Julie Christie","film":"Darling","date":"April 18, 1966","age":25 ,"gender":"female","role":"Best Actress"},
{"name":"Elizabeth Taylor","film":"Who's Afraid of Virginia Woolf?","date":"April 10, 1967","age":35 ,"gender":"female","role":"Best Actress"},
{"name":"Katharine Hepburn","film":"Guess Who's Coming to Dinner","date":"April 10, 1968","age":60 ,"gender":"female","role":"Best Actress"},
{"name":"Katharine Hepburn","film":"The Lion in Winter","date":"April 14, 1969","age":61 ,"gender":"female","role":"Best Actress"},
{"name":"Barbra Streisand","film":"Funny Girl","date":"April 14, 1969","age":26 ,"gender":"female","role":"Best Actress"},
{"name":"Maggie Smith","film":"The Prime of Miss Jean Brodie","date":"April 7, 1970","age":35 ,"gender":"female","role":"Best Actress"},
{"name":"Glenda Jackson","film":"Women in Love","date":"April 15, 1971","age":34 ,"gender":"female","role":"Best Actress"},
{"name":"Jane Fonda","film":"Klute","date":"April 10, 1972","age":34 ,"gender":"female","role":"Best Actress"},
{"name":"Liza Minnelli","film":"Cabaret","date":"March 27, 1973","age":27 ,"gender":"female","role":"Best Actress"},
{"name":"Glenda Jackson","film":"A Touch of Class","date":"April 2, 1974","age":37 ,"gender":"female","role":"Best Actress"},
{"name":"Ellen Burstyn","film":"Alice Doesn't Live Here Anymore","date":"April 8, 1975","age":42 ,"gender":"female","role":"Best Actress"},
{"name":"Louise Fletcher","film":"One Flew Over the Cuckoo's Nest","date":"March 29, 1976","age":41 ,"gender":"female","role":"Best Actress"},
{"name":"Faye Dunaway","film":"Network","date":"March 28, 1977","age":36 ,"gender":"female","role":"Best Actress"},
{"name":"Diane Keaton","film":"Annie Hall","date":"April 3, 1978","age":32 ,"gender":"female","role":"Best Actress"},
{"name":"Jane Fonda","film":"Coming Home","date":"April 9, 1979","age":41 ,"gender":"female","role":"Best Actress"},
{"name":"Sally Field","film":"Norma Rae","date":"April 14, 1980","age":33 ,"gender":"female","role":"Best Actress"},
{"name":"Sissy Spacek","film":"Coal Miner's Daughter","date":"March 31, 1981","age":31 ,"gender":"female","role":"Best Actress"},
{"name":"Katharine Hepburn","film":"On Golden Pond","date":"March 29, 1982","age":74 ,"gender":"female","role":"Best Actress"},
{"name":"Meryl Streep","film":"Sophie's Choice","date":"April 11, 1983","age":33 ,"gender":"female","role":"Best Actress"},
{"name":"Shirley MacLaine","film":"Terms of Endearment","date":"April 9, 1984","age":49 ,"gender":"female","role":"Best Actress"},
{"name":"Sally Field","film":"Places in the Heart","date":"March 25, 1985","age":38 ,"gender":"female","role":"Best Actress"},
{"name":"Geraldine Page","film":"The Trip to Bountiful","date":"March 24, 1986","age":61 ,"gender":"female","role":"Best Actress"},
{"name":"Marlee Matlin","film":"Children of a Lesser God","date":"March 30, 1987","age":21 ,"gender":"female","role":"Best Actress"},
{"name":"Cher","film":"Moonstruck","date":"April 11, 1988","age":41 ,"gender":"female","role":"Best Actress"},
{"name":"Jodie Foster","film":"The Accused","date":"March 27, 1989","age":26 ,"gender":"female","role":"Best Actress"},
{"name":"Jessica Tandy","film":"Driving Miss Daisy","date":"March 26, 1990","age":80 ,"gender":"female","role":"Best Actress"},
{"name":"Kathy Bates","film":"Misery","date":"March 25, 1991","age":42 ,"gender":"female","role":"Best Actress"},
{"name":"Jodie Foster","film":"The Silence of the Lambs","date":"March 30, 1992","age":29 ,"gender":"female","role":"Best Actress"},
{"name":"Emma Thompson","film":"Howards End","date":"March 29, 1993","age":33 ,"gender":"female","role":"Best Actress"},
{"name":"Holly Hunter","film":"The Piano","date":"March 21, 1994","age":36 ,"gender":"female","role":"Best Actress"},
{"name":"Jessica Lange","film":"Blue Sky","date":"March 27, 1995","age":45 ,"gender":"female","role":"Best Actress"},
{"name":"Susan Sarandon","film":"Dead Man Walking","date":"March 25, 1996","age":49 ,"gender":"female","role":"Best Actress"},
{"name":"Frances McDormand","film":"Fargo","date":"March 24, 1997","age":39 ,"gender":"female","role":"Best Actress"},
{"name":"Helen Hunt","film":"As Good as It Gets","date":"March 23, 1998","age":34 ,"gender":"female","role":"Best Actress"},
{"name":"Gwyneth Paltrow","film":"Shakespeare in Love","date":"March 21, 1999","age":26 ,"gender":"female","role":"Best Actress"},
{"name":"Hilary Swank","film":"Boys Don't Cry","date":"March 26, 2000","age":25 ,"gender":"female","role":"Best Actress"},
{"name":"Julia Roberts","film":"Erin Brockovich","date":"March 25, 2001","age":33 ,"gender":"female","role":"Best Actress"},
{"name":"Halle Berry","film":"Monster's Ball","date":"March 24, 2002","age":35 ,"gender":"female","role":"Best Actress"},
{"name":"Nicole Kidman","film":"The Hours","date":"March 23, 2003","age":35 ,"gender":"female","role":"Best Actress"},
{"name":"Charlize Theron","film":"Monster","date":"February 29, 2004","age":28 ,"gender":"female","role":"Best Actress"},
{"name":"Hilary Swank","film":"Million Dollar Baby","date":"February 27, 2005","age":30 ,"gender":"female","role":"Best Actress"},
{"name":"Reese Witherspoon","film":"Walk the Line","date":"March 5, 2006","age":29 ,"gender":"female","role":"Best Actress"},
{"name":"Helen Mirren","film":"The Queen","date":"February 25, 2007","age":61 ,"gender":"female","role":"Best Actress"},
{"name":"Marion Cotillard","film":"La Vie en rose","date":"February 24, 2008","age":32 ,"gender":"female","role":"Best Actress"},
{"name":"Kate Winslet","film":"The Reader","date":"February 22, 2009","age":33 ,"gender":"female","role":"Best Actress"},
{"name":"Sandra Bullock","film":"The Blind Side","date":"March 7, 2010","age":45 ,"gender":"female","role":"Best Actress"},
{"name":"Natalie Portman","film":"Black Swan","date":"February 27, 2011","age":29 ,"gender":"female","role":"Best Actress"},
{"name":"Meryl Streep","film":"The Iron Lady","date":"February 26, 2012","age":62 ,"gender":"female","role":"Best Actress"},
{"name":"Jennifer Lawrence","film":"Silver Linings Playbook","date":"February 24, 2013","age":22 ,"gender":"female","role":"Best Actress"},
{"name":"Walter Brennan","film":"Come and Get It","date":"March 4, 1937","age":42 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Joseph Schildkraut","film":"The Life of Emile Zola","date":"March 10, 1938","age":41 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Walter Brennan","film":"Kentucky","date":"February 23, 1939","age":44 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Thomas Mitchell","film":"Stagecoach","date":"February 29, 1940","age":47 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Walter Brennan","film":"The Westerner","date":"February 27, 1941","age":46 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Donald Crisp","film":"How Green Was My Valley","date":"February 26, 1942","age":59 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Van Heflin","film":"Johnny Eager","date":"March 4, 1943","age":32 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Charles Coburn","film":"The More the Merrier","date":"March 2, 1944","age":66 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Barry Fitzgerald","film":"Going My Way","date":"March 15, 1945","age":57 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"James Dunn","film":"A Tree Grows in Brooklyn","date":"March 7, 1946","age":44 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Harold Russell","film":"The Best Years of Our Lives","date":"March 13, 1947","age":33 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Edmund Gwenn","film":"Miracle on 34th Street","date":"March 20, 1948","age":70 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Walter Huston","film":"The Treasure of the Sierra Madre","date":"March 24, 1949","age":64 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Dean Jagger","film":"Twelve O'Clock High","date":"March 23, 1950","age":46 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"George Sanders","film":"All About Eve","date":"March 29, 1951","age":44 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Karl Malden","film":"A Streetcar Named Desire","date":"March 30, 1952","age":40 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Anthony Quinn","film":"Viva Zapata!","date":"March 19, 1953","age":37 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Frank Sinatra","film":"From Here to Eternity","date":"March 25, 1954","age":38 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Edmond O'Brien","film":"The Barefoot Contessa","date":"March 30, 1955","age":39 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Jack Lemmon","film":"Mister Roberts","date":"March 21, 1956","age":31 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Anthony Quinn","film":"Lust for Life","date":"March 27, 1957","age":41 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Red Buttons","film":"Sayonara","date":"March 26, 1958","age":39 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Burl Ives","film":"The Big Country","date":"April 6, 1959","age":49 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Hugh Griffith","film":"Ben-Hur","date":"April 4, 1960","age":47 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Peter Ustinov","film":"Spartacus","date":"April 17, 1961","age":40 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"George Chakiris","film":"West Side Story","date":"April 9, 1962","age":27 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Ed Begley","film":"Sweet Bird of Youth","date":"April 8, 1963","age":62 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Melvyn Douglas","film":"Hud","date":"April 13, 1964","age":63 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Peter Ustinov","film":"Topkapi","date":"April 5, 1965","age":43 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Martin Balsam","film":"A Thousand Clowns","date":"April 18, 1966","age":46 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Walter Matthau","film":"The Fortune Cookie","date":"April 10, 1967","age":46 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"George Kennedy","film":"Cool Hand Luke","date":"April 10, 1968","age":43 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Jack Albertson","film":"The Subject Was Roses","date":"April 14, 1969","age":61 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Gig Young","film":"They Shoot Horses, Don't They?","date":"April 7, 1970","age":56 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"John Mills","film":"Ryan's Daughter","date":"April 15, 1971","age":63 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Ben Johnson","film":"The Last Picture Show","date":"April 10, 1972","age":53 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Joel Grey","film":"Cabaret","date":"March 27, 1973","age":40 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"John Houseman","film":"The Paper Chase","date":"April 2, 1974","age":71 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Robert De Niro","film":"The Godfather Part II","date":"April 8, 1975","age":31 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"George Burns","film":"The Sunshine Boys","date":"March 29, 1976","age":80 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Jason Robards","film":"All the President's Men","date":"March 28, 1977","age":54 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Jason Robards","film":"Julia","date":"April 3, 1978","age":55 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Christopher Walken","film":"The Deer Hunter","date":"April 9, 1979","age":36 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Melvyn Douglas","film":"Being There","date":"April 14, 1980","age":79 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Timothy Hutton","film":"Ordinary People","date":"March 31, 1981","age":20 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"John Gielgud","film":"Arthur","date":"March 29, 1982","age":77 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Louis Gossett, Jr.","film":"An Officer and a Gentleman","date":"April 11, 1983","age":46 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Jack Nicholson","film":"Terms of Endearment","date":"April 9, 1984","age":46 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Haing S. Ngor","film":"The Killing Fields","date":"March 25, 1985","age":45 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Don Ameche","film":"Cocoon","date":"March 24, 1986","age":77 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Michael Caine","film":"Hannah and Her Sisters","date":"March 30, 1987","age":54 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Sean Connery","film":"The Untouchables","date":"April 11, 1988","age":57 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Kevin Kline","film":"A Fish Called Wanda","date":"March 27, 1989","age":41 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Denzel Washington","film":"Glory","date":"March 26, 1990","age":35 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Joe Pesci","film":"Goodfellas","date":"March 25, 1991","age":48 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Jack Palance","film":"City Slickers","date":"March 30, 1992","age":73 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Gene Hackman","film":"Unforgiven","date":"March 29, 1993","age":63 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Tommy Lee Jones","film":"The Fugitive","date":"March 21, 1994","age":47 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Martin Landau","film":"Ed Wood","date":"March 27, 1995","age":66 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Kevin Spacey","film":"The Usual Suspects","date":"March 25, 1996","age":36 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Cuba Gooding, Jr.","film":"Jerry Maguire","date":"March 24, 1997","age":29 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Robin Williams","film":"Good Will Hunting","date":"March 23, 1998","age":46 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"James Coburn","film":"Affliction","date":"March 21, 1999","age":70 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Michael Caine","film":"The Cider House Rules","date":"March 26, 2000","age":67 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Benicio del Toro","film":"Traffic","date":"March 25, 2001","age":34 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Jim Broadbent","film":"Iris","date":"March 24, 2002","age":52 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Chris Cooper","film":"Adaptation","date":"March 23, 2003","age":51 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Tim Robbins","film":"Mystic River","date":"February 29, 2004","age":45 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Morgan Freeman","film":"Million Dollar Baby","date":"February 27, 2005","age":67 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"George Clooney","film":"Syriana","date":"March 5, 2006","age":44 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Alan Arkin","film":"Little Miss Sunshine","date":"February 25, 2007","age":72 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Javier Bardem","film":"No Country for Old Men","date":"February 24, 2008","age":38 ,"gender":"male","role":"Best Supporting Actor"},
// {"name":"Heath Ledger","film":"The Dark Knight","date":"February 22, 2009","age":N/A[1],"gender":"male","role":"Best Supporting Actor"},
{"name":"Christoph Waltz","film":"Inglourious Basterds","date":"March 7, 2010","age":53 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Christian Bale","film":"The Fighter","date":"February 27, 2011","age":37 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Christopher Plummer","film":"Beginners","date":"February 26, 2012","age":82 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Christoph Waltz","film":"Django Unchained","date":"February 24, 2013","age":56 ,"gender":"male","role":"Best Supporting Actor"},
{"name":"Gale Sondergaard","film":"Anthony Adverse","date":"March 4, 1937","age":38 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Alice Brady","film":"In Old Chicago","date":"March 10, 1938","age":45 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Fay Bainter","film":"Jezebel","date":"February 23, 1939","age":45 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Hattie McDaniel","film":"Gone with the Wind","date":"February 29, 1940","age":44 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Jane Darwell","film":"The Grapes of Wrath","date":"February 27, 1941","age":61 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Mary Astor","film":"The Great Lie","date":"February 26, 1942","age":35 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Teresa Wright","film":"Mrs. Miniver","date":"March 4, 1943","age":24 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Katina Paxinou","film":"For Whom the Bell Tolls","date":"March 2, 1944","age":43 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Ethel Barrymore","film":"None but the Lonely Heart","date":"March 15, 1945","age":65 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Anne Revere","film":"National Velvet","date":"March 7, 1946","age":42 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Anne Baxter","film":"The Razor's Edge","date":"March 13, 1947","age":23 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Celeste Holm","film":"Gentleman's Agreement","date":"March 20, 1948","age":30 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Claire Trevor","film":"Key Largo","date":"March 24, 1949","age":39 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Mercedes McCambridge","film":"All the King's Men","date":"March 23, 1950","age":34 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Josephine Hull","film":"Harvey","date":"March 29, 1951","age":65 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Kim Hunter","film":"A Streetcar Named Desire","date":"March 30, 1952","age":29 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Gloria Grahame","film":"The Bad and the Beautiful","date":"March 19, 1953","age":29 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Donna Reed","film":"From Here to Eternity","date":"March 25, 1954","age":33 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Eva Marie Saint","film":"On the Waterfront","date":"March 30, 1955","age":30 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Jo Van Fleet","film":"East of Eden","date":"March 21, 1956","age":41 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Dorothy Malone","film":"Written on the Wind","date":"March 27, 1957","age":32 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Miyoshi Umeki","film":"Sayonara","date":"March 26, 1958","age":28 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Wendy Hiller","film":"Separate Tables","date":"April 6, 1959","age":46 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Shelley Winters","film":"The Diary of Anne Frank","date":"April 4, 1960","age":39 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Shirley Jones","film":"Elmer Gantry","date":"April 17, 1961","age":27 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Rita Moreno","film":"West Side Story","date":"April 9, 1962","age":30 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Patty Duke","film":"The Miracle Worker","date":"April 8, 1963","age":16 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Margaret Rutherford","film":"The V.I.P.s","date":"April 13, 1964","age":71 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Lila Kedrova","film":"Zorba the Greek","date":"April 5, 1965","age":46 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Shelley Winters","film":"A Patch of Blue","date":"April 18, 1966","age":45 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Sandy Dennis","film":"Who's Afraid of Virginia Woolf","date":"April 10, 1967","age":29 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Estelle Parsons","film":"Bonnie and Clyde","date":"April 10, 1968","age":40 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Ruth Gordon","film":"Rosemary's Baby","date":"April 14, 1969","age":72 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Goldie Hawn","film":"Cactus Flower","date":"April 7, 1970","age":24 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Helen Hayes","film":"Airport","date":"April 15, 1971","age":70 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Cloris Leachman","film":"The Last Picture Show","date":"April 10, 1972","age":45 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Eileen Heckart","film":"Butterflies Are Free","date":"March 27, 1973","age":53 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Tatum O'Neal","film":"Paper Moon","date":"April 2, 1974","age":10 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Ingrid Bergman","film":"Murder on the Orient Express","date":"April 8, 1975","age":59 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Lee Grant","film":"Shampoo","date":"March 29, 1976","age":48 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Beatrice Straight","film":"Network","date":"March 28, 1977","age":62 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Vanessa Redgrave","film":"Julia","date":"April 3, 1978","age":41 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Maggie Smith","film":"California Suite","date":"April 9, 1979","age":44 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Meryl Streep","film":"Kramer vs. Kramer","date":"April 14, 1980","age":30 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Mary Steenburgen","film":"Melvin and Howard","date":"March 31, 1981","age":28 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Maureen Stapleton","film":"Reds","date":"March 29, 1982","age":56 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Jessica Lange","film":"Tootsie","date":"April 11, 1983","age":33 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Linda Hunt","film":"The Year of Living Dangerously","date":"April 9, 1984","age":39 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Peggy Ashcroft","film":"A Passage to India","date":"March 25, 1985","age":77 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Anjelica Huston","film":"Prizzi's Honor","date":"March 24, 1986","age":34 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Dianne Wiest","film":"Hannah and Her Sisters","date":"March 30, 1987","age":39 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Olympia Dukakis","film":"Moonstruck","date":"April 11, 1988","age":56 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Geena Davis","film":"The Accidental Tourist","date":"March 27, 1989","age":33 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Brenda Fricker","film":"My Left Foot","date":"March 26, 1990","age":45 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Whoopi Goldberg","film":"Ghost","date":"March 25, 1991","age":35 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Mercedes Ruehl","film":"The Fisher King","date":"March 30, 1992","age":44 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Marisa Tomei","film":"My Cousin Vinny","date":"March 29, 1993","age":28 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Anna Paquin","film":"The Piano","date":"March 21, 1994","age":11 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Dianne Wiest","film":"Bullets Over Broadway","date":"March 27, 1995","age":46 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Mira Sorvino","film":"Mighty Aphrodite","date":"March 25, 1996","age":28 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Juliette Binoche","film":"The English Patient","date":"March 24, 1997","age":33 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Kim Basinger","film":"L.A. Confidential","date":"March 23, 1998","age":44 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Judi Dench","film":"Shakespeare in Love","date":"March 21, 1999","age":64 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Angelina Jolie","film":"Girl, Interrupted","date":"March 26, 2000","age":24 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Marcia Gay Harden","film":"Pollock","date":"March 25, 2001","age":41 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Jennifer Connelly","film":"A Beautiful Mind","date":"March 24, 2002","age":31 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Catherine Zeta-Jones","film":"Chicago","date":"March 23, 2003","age":33 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Renée Zellweger","film":"Cold Mountain","date":"February 29, 2004","age":34 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Cate Blanchett","film":"The Aviator","date":"February 27, 2005","age":35 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Rachel Weisz","film":"The Constant Gardener","date":"March 5, 2006","age":35 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Jennifer Hudson","film":"Dreamgirls","date":"February 25, 2007","age":25 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Tilda Swinton","film":"Michael Clayton","date":"February 24, 2008","age":47 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Penélope Cruz","film":"Vicky Cristina Barcelona","date":"February 22, 2009","age":34 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Monique Imes","film":"Precious","date":"March 7, 2010","age":42 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Melissa Leo","film":"The Fighter","date":"February 27, 2011","age":50 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Octavia Spencer","film":"The Help","date":"February 26, 2012","age":39 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Anne Hathaway","film":"Les Misérables","date":"February 24, 2013","age":30 ,"gender":"female","role":"Best Supporting Actress"},
{"name":"Emil Jannings","film":"2 roles; see note[1]","date":"May 16, 1929","age":44 ,"gender":"male","role":"Best Actor"},
{"name":"Warner Baxter","film":"In Old Arizona","date":"April 3, 1930","age":41 ,"gender":"male","role":"Best Actor"},
{"name":"George Arliss","film":"Disraeli","date":"November 5, 1930","age":62 ,"gender":"male","role":"Best Actor"},
{"name":"Lionel Barrymore","film":"A Free Soul","date":"November 10, 1931","age":53 ,"gender":"male","role":"Best Actor"},
{"name":"Wallace Beery","film":"The Champ","date":"November 18, 1932","age":47 ,"gender":"male","role":"Best Actor"},
{"name":"Fredric March","film":"Dr. Jekyll and Mr. Hyde","date":"November 18, 1932","age":35 ,"gender":"male","role":"Best Actor"},
{"name":"Charles Laughton","film":"The Private Life of Henry VIII","date":"March 16, 1934","age":34 ,"gender":"male","role":"Best Actor"},
{"name":"Clark Gable","film":"It Happened One Night","date":"February 27, 1935","age":34 ,"gender":"male","role":"Best Actor"},
{"name":"Victor McLaglen","film":"The Informer","date":"March 5, 1936","age":49 ,"gender":"male","role":"Best Actor"},
{"name":"Paul Muni","film":"The Story of Louis Pasteur","date":"March 4, 1937","age":41 ,"gender":"male","role":"Best Actor"},
{"name":"Spencer Tracy","film":"Captains Courageous","date":"March 10, 1938","age":37 ,"gender":"male","role":"Best Actor"},
{"name":"Spencer Tracy","film":"Boys Town","date":"February 23, 1939","age":38 ,"gender":"male","role":"Best Actor"},
{"name":"Robert Donat","film":"Goodbye, Mr. Chips","date":"February 29, 1940","age":34 ,"gender":"male","role":"Best Actor"},
{"name":"James Stewart","film":"The Philadelphia Story","date":"February 27, 1941","age":32 ,"gender":"male","role":"Best Actor"},
{"name":"Gary Cooper","film":"Sergeant York","date":"February 26, 1942","age":40 ,"gender":"male","role":"Best Actor"},
{"name":"James Cagney","film":"Yankee Doodle Dandy","date":"March 4, 1943","age":43 ,"gender":"male","role":"Best Actor"},
{"name":"Paul Lukas","film":"Watch on the Rhine","date":"March 2, 1944","age":48 ,"gender":"male","role":"Best Actor"},
{"name":"Bing Crosby","film":"Going My Way","date":"March 15, 1945","age":41 ,"gender":"male","role":"Best Actor"},
{"name":"Ray Milland","film":"The Lost Weekend","date":"March 7, 1946","age":39 ,"gender":"male","role":"Best Actor"},
{"name":"Fredric March","film":"The Best Years of Our Lives","date":"March 13, 1947","age":49 ,"gender":"male","role":"Best Actor"},
{"name":"Ronald Colman","film":"A Double Life","date":"March 20, 1948","age":57 ,"gender":"male","role":"Best Actor"},
{"name":"Laurence Olivier","film":"Hamlet","date":"March 24, 1949","age":41 ,"gender":"male","role":"Best Actor"},
{"name":"Broderick Crawford","film":"All the King's Men","date":"March 23, 1950","age":38 ,"gender":"male","role":"Best Actor"},
{"name":"José Ferrer","film":"Cyrano de Bergerac","date":"March 29, 1951","age":39 ,"gender":"male","role":"Best Actor"},
{"name":"Humphrey Bogart","film":"The African Queen","date":"March 30, 1952","age":52 ,"gender":"male","role":"Best Actor"},
{"name":"Gary Cooper","film":"High Noon","date":"March 19, 1953","age":51 ,"gender":"male","role":"Best Actor"},
{"name":"William Holden","film":"Stalag 17","date":"March 25, 1954","age":35 ,"gender":"male","role":"Best Actor"},
{"name":"Marlon Brando","film":"On the Waterfront","date":"March 30, 1955","age":30 ,"gender":"male","role":"Best Actor"},
{"name":"Ernest Borgnine","film":"Marty","date":"March 21, 1956","age":39 ,"gender":"male","role":"Best Actor"},
{"name":"Yul Brynner","film":"The King and I","date":"March 27, 1957","age":36 ,"gender":"male","role":"Best Actor"},
{"name":"Alec Guinness","film":"The Bridge on the River Kwai","date":"March 26, 1958","age":43 ,"gender":"male","role":"Best Actor"},
{"name":"David Niven","film":"Separate Tables","date":"April 6, 1959","age":49 ,"gender":"male","role":"Best Actor"},
{"name":"Charlton Heston","film":"Ben-Hur","date":"April 4, 1960","age":36 ,"gender":"male","role":"Best Actor"},
{"name":"Burt Lancaster","film":"Elmer Gantry","date":"April 17, 1961","age":47 ,"gender":"male","role":"Best Actor"},
{"name":"Maximilian Schell","film":"Judgment at Nuremberg","date":"April 9, 1962","age":31 ,"gender":"male","role":"Best Actor"},
{"name":"Gregory Peck","film":"To Kill a Mockingbird","date":"April 8, 1963","age":47 ,"gender":"male","role":"Best Actor"},
{"name":"Sidney Poitier","film":"Lilies of the Field","date":"April 13, 1964","age":37 ,"gender":"male","role":"Best Actor"},
{"name":"Rex Harrison","film":"My Fair Lady","date":"April 5, 1965","age":57 ,"gender":"male","role":"Best Actor"},
{"name":"Lee Marvin","film":"Cat Ballou","date":"April 18, 1966","age":42 ,"gender":"male","role":"Best Actor"},
{"name":"Paul Scofield","film":"A Man for All Seasons","date":"April 10, 1967","age":45 ,"gender":"male","role":"Best Actor"},
{"name":"Rod Steiger","film":"In the Heat of the Night","date":"April 10, 1968","age":42 ,"gender":"male","role":"Best Actor"},
{"name":"Cliff Robertson","film":"Charly","date":"April 14, 1969","age":45 ,"gender":"male","role":"Best Actor"},
{"name":"John Wayne","film":"True Grit","date":"April 7, 1970","age":62 ,"gender":"male","role":"Best Actor"},
{"name":"George C. Scott","film":"Patton","date":"April 15, 1971","age":43 ,"gender":"male","role":"Best Actor"},
{"name":"Gene Hackman","film":"The French Connection","date":"April 10, 1972","age":42 ,"gender":"male","role":"Best Actor"},
{"name":"Marlon Brando","film":"The Godfather","date":"March 27, 1973","age":48 ,"gender":"male","role":"Best Actor"},
{"name":"Jack Lemmon","film":"Save the Tiger","date":"April 2, 1974","age":49 ,"gender":"male","role":"Best Actor"},
{"name":"Art Carney","film":"Harry and Tonto","date":"April 8, 1975","age":56 ,"gender":"male","role":"Best Actor"},
{"name":"Jack Nicholson","film":"One Flew Over the Cuckoo's Nest","date":"March 29, 1976","age":38 ,"gender":"male","role":"Best Actor"},
{"name":"Richard Dreyfuss","film":"The Goodbye Girl","date":"April 3, 1978","age":30 ,"gender":"male","role":"Best Actor"},
{"name":"Jon Voight","film":"Coming Home","date":"April 9, 1979","age":40 ,"gender":"male","role":"Best Actor"},
{"name":"Dustin Hoffman","film":"Kramer vs. Kramer","date":"April 14, 1980","age":42 ,"gender":"male","role":"Best Actor"},
{"name":"Robert De Niro","film":"Raging Bull","date":"March 31, 1981","age":37 ,"gender":"male","role":"Best Actor"},
{"name":"Henry Fonda","film":"On Golden Pond","date":"March 29, 1982","age":76 ,"gender":"male","role":"Best Actor"},
{"name":"Ben Kingsley","film":"Gandhi","date":"April 11, 1983","age":39 ,"gender":"male","role":"Best Actor"},
{"name":"Robert Duvall","film":"Tender Mercies","date":"April 9, 1984","age":53 ,"gender":"male","role":"Best Actor"},
{"name":"F. Murray Abraham","film":"Amadeus","date":"March 25, 1985","age":45 ,"gender":"male","role":"Best Actor"},
{"name":"William Hurt","film":"Kiss of the Spider Woman","date":"March 24, 1986","age":36 ,"gender":"male","role":"Best Actor"},
{"name":"Paul Newman","film":"The Color of Money","date":"March 30, 1987","age":62 ,"gender":"male","role":"Best Actor"},
{"name":"Michael Douglas","film":"Wall Street","date":"April 11, 1988","age":43 ,"gender":"male","role":"Best Actor"},
{"name":"Dustin Hoffman","film":"Rain Man","date":"March 27, 1989","age":51 ,"gender":"male","role":"Best Actor"},
{"name":"Daniel Day-Lewis","film":"My Left Foot","date":"March 26, 1990","age":32 ,"gender":"male","role":"Best Actor"},
{"name":"Jeremy Irons","film":"Reversal of Fortune","date":"March 25, 1991","age":42 ,"gender":"male","role":"Best Actor"},
{"name":"Anthony Hopkins","film":"The Silence of the Lambs","date":"March 30, 1992","age":54 ,"gender":"male","role":"Best Actor"},
{"name":"Al Pacino","film":"Scent of a Woman","date":"March 29, 1993","age":52 ,"gender":"male","role":"Best Actor"},
{"name":"Tom Hanks","film":"Philadelphia","date":"March 21, 1994","age":37 ,"gender":"male","role":"Best Actor"},
{"name":"Tom Hanks","film":"Forrest Gump","date":"March 27, 1995","age":38 ,"gender":"male","role":"Best Actor"},
{"name":"Nicolas Cage","film":"Leaving Las Vegas","date":"March 25, 1996","age":32 ,"gender":"male","role":"Best Actor"},
{"name":"Geoffrey Rush","film":"Shine","date":"March 24, 1997","age":45 ,"gender":"male","role":"Best Actor"},
{"name":"Jack Nicholson","film":"As Good as It Gets","date":"March 23, 1998","age":60 ,"gender":"male","role":"Best Actor"},
{"name":"Roberto Benigni","film":"Life Is Beautiful","date":"March 21, 1999","age":46 ,"gender":"male","role":"Best Actor"},
{"name":"Kevin Spacey","film":"American Beauty","date":"March 26, 2000","age":40 ,"gender":"male","role":"Best Actor"},
{"name":"Russell Crowe","film":"Gladiator","date":"March 25, 2001","age":36 ,"gender":"male","role":"Best Actor"},
{"name":"Denzel Washington","film":"Training Day","date":"March 24, 2002","age":47 ,"gender":"male","role":"Best Actor"},
{"name":"Adrien Brody","film":"The Pianist","date":"March 23, 2003","age":29 ,"gender":"male","role":"Best Actor"},
{"name":"Sean Penn","film":"Mystic River","date":"February 29, 2004","age":43 ,"gender":"male","role":"Best Actor"},
{"name":"Jamie Foxx","film":"Ray","date":"February 27, 2005","age":37 ,"gender":"male","role":"Best Actor"},
{"name":"Philip Seymour Hoffman","film":"Capote","date":"March 5, 2006","age":38 ,"gender":"male","role":"Best Actor"},
{"name":"Forest Whitaker","film":"The Last King of Scotland","date":"February 25, 2007","age":45 ,"gender":"male","role":"Best Actor"},
{"name":"Daniel Day-Lewis","film":"There Will Be Blood","date":"February 24, 2008","age":50 ,"gender":"male","role":"Best Actor"},
{"name":"Sean Penn","film":"Milk","date":"February 22, 2009","age":48 ,"gender":"male","role":"Best Actor"},
{"name":"Jeff Bridges","film":"Crazy Heart","date":"March 7, 2010","age":60 ,"gender":"male","role":"Best Actor"},
{"name":"Colin Firth","film":"The King's Speech","date":"February 27, 2011","age":50 ,"gender":"male","role":"Best Actor"},
{"name":"Jean Dujardin","film":"The Artist","date":"February 26, 2012","age":39 ,"gender":"male","role":"Best Actor"},
{"name":"Daniel Day-Lewis","film":"Lincoln","date":"February 24, 2013","age":55 ,"gender":"male","role":"Best Actor"}]